fix types and remove useless method
lettdigital/lett-log pull request #13
Opened 2022-10-31 14:41 UTC by IgorSiilva

2022-10-31 14:43 UTC, Hiagozeroum commented
Essa alteração corrige algum problema por causa dos parametros?

2022-10-31 14:49 UTC, deleuterio requested changes

2022-10-31 14:49 UTC, deleuterio commented on index.js
> +                        colorize(),
@IgorSiilva pq tirou isso?

2022-10-31 14:53 UTC, IgorSiilva commented on index.js
> +                        colorize(),
Isso não altera nada, o combine é pra combinar varias formatações em criar uma unica, o colorize de fato colore o texto, mas o printf não muda nada, já é usado lá em baixo, então é meio que uma duplicação

2022-10-31 14:53 UTC, IgorSiilva commented on index.js
> +                        colorize(),
ai deixei o colorize logo como padrão

2022-10-31 14:53 UTC, IgorSiilva commented
> Essa alteração corrige algum problema por causa dos parametros?

No typescript não dava pra usar pq alguns parametros estão tipados errados, como obrigatorio e no codigo não é obrigatorio.

2022-10-31 15:00 UTC, deleuterio commented on index.js
> +                        colorize(),
Na real não é isso que faz. coloquei isso por causa disso aqui:
https://github.com/lettdigital/lett-log/releases/tag/v2.2.0

é importante desabilitar de cores quando é para printar num arquivo de texto

2022-10-31 15:01 UTC, deleuterio commented on index.js
> +                        colorize(),
```suggestion
                        colors ? colorize() : printf(log => log),
```

2022-10-31 19:12 UTC, IgorSiilva commented on index.js
> +                        colorize(),
Saquei, sabia n

2022-10-31 20:48 UTC, deleuterio submitted a review, later dismissed
Antes de mergir tem que atualizar changelog e  rodar `npm run patch`

2022-11-01 12:34 UTC, Hiagozeroum submitted a review, later dismissed

2022-11-01 20:26 UTC, deleuterio approved these changes

2022-11-01 20:26 UTC, merged